sudo: false
language: node_js
node_js: "10"
before_install:
  - npm install util
  - npm install puppeteer
script: ./make.js test
notifications:
  email: false
branches:
  except:
    - experimental
    - 1.43
    - commands
