"QOL stuff
syntax on
set nocompatible
set shortmess+=I
set number
set backspace=indent,eol,start
set smartindent
set hidden
set ignorecase
set smartcase
set incsearch
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
filetype plugin on
set noerrorbells visualbell t_vb=
set linebreak
set noendofline
set nofixendofline

"always start in normal mode
set t_u7=
set ambw=double

"block for norm, beam for insert
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

"4 space wide tab characters
set shiftwidth=0
set tabstop=4
set noexpandtab

"tab completion when typing editor commands
set wildmode=longest,list,full
set wildmenu

"dumb key - literally nobody uses it anyways
nmap Q <Nop>

"run script in shellcheck
map <leader>s :!clear && shellcheck -x %<CR>

nnoremap cl S<Esc>

"shift+s enables sed mode
nnoremap S :%s//g<Left><Left>

"some 'macros'
nnoremap <Leader>so :source ~/.config/vim/vimrc<Enter>
nnoremap "l I"<Esc>
nnoremap #l I#<Esc>

"real macros

"disable automatic commenting on newline
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

"set relative numbers while editing and absolute while not
set number
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set nornu | endif
	autocmd BufLeave,FocusLost,InsertEnter,WinLeave * if &nu | set rnu | endif
augroup END

"toggle spell check
map <leader>sc :setlocal spell! spelllang=en_us<CR>

"delete trailing whitespace and newlines at end of file on save
autocmd BufWritePre * let currPos = getpos(".")
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritePre * %s/\n\+\%$//e
autocmd BufWritePre *.[ch] %s/\%$/\r/e

"perform dot commands on visual blocks
vnoremap . :normal .<CR>

"traditional copy paste commands using device register
vnoremap <C-C> "*y :let @+=@*<CR>"
map <S-Insert> "+P"
map <C-Shift-V> "+P"

"enforce h and l movement in normal mode
nnoremap <Left> :echo ""<Enter>
nnoremap <Right> :echo ""<Enter>

"map p to P since p sucks
map p P

"let arrow keys always be g<Arrow>
map <Up> g<Up>
map <Down> g<Down>
vnoremap j gj
vnoremap k gk

"far movement with shift
map H <S-Left>
map L <S-Right>
map J 10j
map K 10k

"syntax highlighting for various file formats
autocmd BufNewFile,BufRead *.bashrc,*.zsh*,.zshrc,config,pacman.conf set syntax=bash
autocmd BufNewFile,BufRead rc.conf,zathurarc set syntax=vim
autocmd BufRead,BufNewFile *.ms,*.me,*.mom,*.man set filetype=groff
autocmd BufRead,BufNewFile *.tex set filetype=tex

"file specific shortcuts and macros
autocmd BufNewFile *.html norm i<!DOCTYPE html>
autocmd BufNewFile *.sh norm i#!/bin/sh

if &filetype ==# 'html'
	nnoremap css i<link rel="stylesheet" href="/css/sitewide.css"><Esc>
	nnoremap br a<br><Esc>
	inoremap <F5> <C-R>=strftime("%b %d, %Y")<CR>
	let @a='i<a href="">link</a>9hi'
endif

if &filetype ==# 'sh'
	nnoremap case icase "$1" in<Enter><Tab>-h) <Enter><Esc>!!basename %<Enter>i<Backspace><Esc>A_help ;; #make sure to include "$@" on other functions<Enter><Esc>Iesac<Esc>
	nnoremap <Leader>binsh ggI<Enter><Up>#!/bin/sh<Esc>
endif
