"QOL stuff
syntax on
set nocompatible
set shortmess+=I
set number
set backspace=indent,eol,start
set hidden
set ignorecase
set smartcase
set incsearch
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
filetype plugin on
set noerrorbells visualbell t_vb=

"enable mouse
"set mouse+=a

"4 space wide tab characters
set shiftwidth=0
set tabstop=4
set noexpandtab

"tab completion when typing editor commands
set wildmode=longest,list,full
set wildmenu

"dumb key - literally nobody uses it anyways
nmap Q <Nop>

"run script in shellcheck
map <leader>s :!clear && shellcheck -x %<CR>

nnoremap cl S<Esc>

"shift+s enables sed mode
nnoremap S :%s//g<Left><Left>

"some 'macros'
nnoremap css i<link rel="stylesheet" href="/css/sitewide.css"><Esc>
nnoremap br a<br><Esc>
nnoremap <C-S-R> :source ~/.config/vim/vimrc<Enter>
nnoremap "l I"<Esc>
nnoremap #l I#<Esc>

"disable automatic commenting on newline
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

"set relative numbers while editing and absolute while not
set number
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set nornu | endif
	autocmd BufLeave,FocusLost,InsertEnter,WinLeave * if &nu | set rnu | endif
augroup END

"toggle spell check
map <leader>sc :setlocal spell! spelllang=en_us<CR>

"fix command mistakes
cnoremap qw wq
cnoremap Wq wq
cnoremap WQ wq
cnoremap Q q
cnoremap Q! q!

"delete trailing whitespace and newlines at end of file on save
autocmd BufWritePre * let currPos = getpos(".")
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritePre * %s/\n\+\%$//e
autocmd BufWritePre *.[ch] %s/\%$/\r/e

"perform dot commands on visual blocks
vnoremap . :normal .<CR>

"traditional copy paste commands using device register
vnoremap <C-C> "*y :let @+=@*<CR>"
map <S-Insert> "+P"
map <C-Shift-V> "+P"

"enforce h and l movement in normal mode
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>

"map p to P since p sucks
map p P

"let arrow keys always be g<Arrow>
map <Up> g<Up>
map <Down> g<Down>
vnoremap j gj
vnoremap k gk

"arrow key shift movement is nice
map H b
map L w
map J <S-Down>
map K <S-Up>

"syntax highlighting for various file formats
autocmd BufNewFile,BufRead *.bashrc,*.zsh*,zshrc,*.khotkeys,*.kksrc,pacman.conf set syntax=bash
autocmd BufNewFile,BufRead rc.conf,zathurarc set syntax=vim
autocmd BufRead,BufNewFile *.ms,*.me,*.mom,*.man set filetype=groff
autocmd BufRead,BufNewFile *.tex set filetype=tex
