export PATH=$PATH:$HOME/.local/bin

do_stuff () {
	#wallpaper automation
	WALLDIR="$HOME/.local/share/wallpapers"
	export WALL="$WALLDIR/$(command ls -1 $WALLDIR | shuf -n 1)"
	xwallpaper --zoom "$WALL"
	wal -q -i "$WALL"

	#thinkpad bindings
	xinput set-prop "/dev/wsmouse" "Device Accel Constant Deceleration" 0.3
	xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
	xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
	xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

	picom & #compositing
	dunst & #notifications
	dwmblocks & #statusbar
	sxhkd & #hotkeys
	setxkbmap -layout us -option caps:super #caps-->super
	xrandr --output default --mode "1600x900"
	sndiod #sound daemon
	exec dwm
}

kill_stuff () {
	doas killall picom
	doas killall dunst
	doas killall sxhkd
	doas killall dwmblocks
	doas killall sndiod
}

restart_stuff () {
	kill_stuff
	do_stuff
}

case "$1" in
	-r) restart_stuff ;;
	-k) kill_stuff ;;
	*) do_stuff ;;
esac
