export PATH=$PATH:$HOME/.local/bin

randbg

if [ "$HOSTNAME" = "think420" ]; then
	xrandr --output default --mode "1600x900"
	#thinkpad bindings
	xinput set-prop "/dev/wsmouse" "Device Accel Constant Deceleration" 0.3
	xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
	xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
	xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5
else if [ "$HOSTNAME" = "pavilion" ]; then
	increase cursor speed
	xinput set-prop 9 321 0.65
fi fi

dunst & dbus-uuidgen --ensure #notifications
picom & #compositor
sxhkd & #keybinds
dwmblocks & #statusbar
plugcheck & #battery monitoring

#train myself to use caps for super
setxkbmap -layout us -option caps:super
setxkbmap -layout us -option super:none

_openbsd() {
	apmd #monitoring
	sndiod #sound daemon
}

case "$OS" in
	Linux) _linux ;;
	OpenBSD) _openbsd ;;
esac

exec dwm
