# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

exec-once = /usr/bin/kwalletd6
#exec-once = waybar
exec-once = /usr/lib/polkit-kde-authentication-agent-1

$mainMod = SUPER

exec-once = sh -c 'echo "\$browser = $(xdg-settings get default-web-browser)" > ~/.config/hypr/browser.conf'
source = ~/.config/hypr/browser.conf
bind = $mainMod, B, exec, gtk-launch $browser
exec-once = hypridle

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$lock = hyprlock

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, $menu
bind = $mainMod, M, layoutmsg, swapwithmaster
#bind = $mainMod, N, exec, kcmshell6 kcm_networkmanagement
bind = $mainMod, N, exec, plasmawindowed org.kde.plasma.networkmanagement
#bind = $mainMod, B, exec, fish -c 'gtk-launch $BROWSER'

bind = $mainMod SHIFT, L, exec, $lock
bind = $mainMod SHIFT, Q, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

animations {
	enabled = no
}

cursor {
	no_warps = true
}

general {
	layout = master
}

input {
	touchpad {
		natural_scroll = true
		scroll_factor = 0.1
	}
}

master {
	new_status = slave
	new_on_top = true
}

binde = $mainMod, H, layoutmsg, mfact -0.05
binde = $mainMod, L, layoutmsg, mfact +0.05
bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, K, layoutmsg, cycleprev
# ----------------------------------------------------- 
# Media & Volume Keys
# -----------------------------------------------------

# Volume control
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Mic mute
bindl  = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Brightness control
bindel = , XF86MonBrightnessUp, exec, brightnessctl s 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Media player controls (Play/Pause, Next, Previous)
bindl  = , XF86AudioPlay, exec, playerctl play-pause
bindl  = , XF86AudioNext, exec, playerctl next
bindl  = , XF86AudioPrev, exec, playerctl previous

#windowrulev2 = float; center; size 400 600, class:^(brave-.*-Default)$
#windowrulev2 = float; center; size 400 600, class:^(org\.kde\.plasmawindowed)$

# Move floating windows with Win + Left Click drag
bindm = $mainMod, mouse:272, movewindow

# Resize floating windows with Win + Right Click drag
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod SHIFT, S, exec, hyprshot -m region -o ~/Pictures/Screenshots

# Regular Fullscreen (Takes over the entire monitor)
bind = $mainMod, F, fullscreen, 0

# Fake Fullscreen (App expands inside its current tiled pane)
bind = $mainMod SHIFT, F, fullscreenstate, -1 2

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move active window to workspace (Win + Shift + [1-5])
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Optional: Scroll through existing workspaces with Win + Mouse Scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
