#!/bin/sh

start() {
	pgrep $1 > /dev/null || $1 &
}

#start programs if not running
start sxhkd
start picom
start bspswallow
start dunst

pgrep polybar && kill $(pgrep polybar)
polybar main &

#workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width	3
bspc config window_gap		5

#wallpaper automation
WALLDIR="$HOME/.local/share/wallpapers"
export WALL="$WALLDIR/$(command ls -1 $WALLDIR | shuf -n 1)"
xwallpaper --zoom "$WALL"
wal -q -i "$WALL"